language: java

addons:
  sonarcloud:
    organization: "hrcornejo"	
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar